# Generated by Django 2.2.5 on 2019-11-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_de_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
