# Generated by Django 2.2.5 on 2019-11-06 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_remove_medico_pacientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='pacientes',
            field=models.ManyToManyField(to='administracion.Paciente'),
        ),
    ]
