# Generated by Django 2.2.5 on 2019-11-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_medico_pacientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='pacientes',
        ),
    ]
