# Generated by Django 2.2.5 on 2019-11-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20191104_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='apellido',
        ),
    ]
